name: Build and deploy ASP.Net Core app to Azure Web App - BeestjeOpEenFeestje

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Restore dependencies using the solution file in the BeestjeOpEenFeestje folder
      - name: Restore Dependencies
        run: dotnet restore BeestjeOpEenFeestje/BeestjeOpEenFeestje.sln

      # Build the solution inside the BeestjeOpEenFeestje folder
      - name: Build with dotnet
        run: dotnet build BeestjeOpEenFeestje/BeestjeOpEenFeestje.sln --configuration Release

      # Publish the app, specifying the .csproj file inside the BeestjeOpEenFeestje folder
      - name: Publish with dotnet
        run: dotnet publish BeestjeOpEenFeestje/BeestjeOpEenFeestje.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B1C9F1C18F6544E08E6DCDE13FCDBDB1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_73723CC1E8A147978E595495FA4030C1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B1B3D9A6EBED4C6EBAA896BAB5D68202 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BeestjeOpEenFeestje'
          slot-name: 'Production'
          package: ${{env.DOTNET_ROOT}}/myapp
